apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator
    newName: harbor-repo.vmware.com/mlops/training-operator
    newTag: v1.0-kubeflow-kubeflow-training
